// <auto-generated />
using System;
using EmployeeDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDatabase.Migrations
{
    [DbContext(typeof(EmployeeDatabaseDbContext))]
    [Migration("20221126091323_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeDatabase.Models.Employee", b =>
                {
                    b.Property<Guid>("EMPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CONTACT")
                        .HasColumnType("int");

                    b.Property<string>("DEGREE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRSTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GENDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LASTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MIDDLENAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SALARY")
                        .HasColumnType("int");

                    b.HasKey("EMPID");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
